Make adapter and example compatible with preCICE v3.0.0
precice/dune-adapter pull request #7
Opened 2024-02-22 16:28 UTC by Fujikawas

2024-03-02 06:17 UTC, IshaanDesai commented on README.md
> +The adapter can be built with:
```suggestion
Build the adapter by running
```

2024-03-02 06:18 UTC, IshaanDesai commented on README.md
>  found in:
```suggestion
The executable `dune-perpendicular-flap` for the perpendicular-flap tutorial case is in:
```

2024-03-02 06:18 UTC, IshaanDesai commented on README.md
> +after the module was built and needs to be copied to the `solid-dune` folder inside the respective tutorial case.
This sentence made sense as a standalone bullet point, but does not have a reading flow. What are we trying to say here?

2024-03-02 06:19 UTC, IshaanDesai commented on dune-precice-howto/examples/dune-perpendicular-flap.cc
> -// vi: set et ts=4 sw=2 sts=2:
These instructions seem important. Are we sure we don't want them here anymore?

2024-03-02 06:28 UTC, IshaanDesai commented on dune-precice/dune-precice/couplinginterface.hh
> +      std::string write_data_name_;
The `const` is now removed for these variables. Is this intentional?

2024-03-02 06:30 UTC, IshaanDesai commented on dune-precice/dune-precice/couplinginterface.hh
> +      bool is_load_required() ;
```suggestion
      bool is_save_required();
      bool is_load_required();
```

2024-03-02 06:33 UTC, IshaanDesai commented on dune-precice/dune-precice/couplinginterface.hh
> +        interface_nodes_ids_.push_back(j*coordinates_of_boundary.N()+i);}
This syntax is difficult to read. It would be better to have the operations inside the if loop on separate lines.

2024-03-02 06:34 UTC, IshaanDesai commented on dune-precice/dune-precice/couplinginterface.hh
> -
? Let us keep empty lines.

2024-03-02 06:39 UTC, IshaanDesai commented on dune-precice/dune-precice/couplinginterface.hh
> +    precice.readData(mesh_name_view,read_data_name_view,interface_nodes_ids_,dt, read_data_span);
```suggestion
    precice.readData(mesh_name_view, read_data_name_view, interface_nodes_ids_, dt, read_data_span);
```

2024-03-02 06:42 UTC, IshaanDesai requested changes
Thanks for the update. Some formatting and code related changes need to be discussed before we can finalize things.

2024-03-05 12:23 UTC, Fujikawas commented on dune-precice-howto/examples/dune-perpendicular-flap.cc
> -// vi: set et ts=4 sw=2 sts=2:
I remove it because when I used `vim` it reformatted the whole file to a very different form, which is far from what we currently have. :/ But I am not sure how we plan to format this whole adapter originally.

2024-03-06 04:43 UTC, IshaanDesai commented on dune-precice-howto/examples/dune-perpendicular-flap.cc
> -// vi: set et ts=4 sw=2 sts=2:
Okay. In that case, these comments do not seem very relevant, and we can remove them.

2024-03-07 12:22 UTC, IshaanDesai commented on dune-precice/dune.module
> +Depends: dune-common (>= 2.9) dune-istl (>= 2.9) dune-functions (>= 2.9)
This change is not relevant to preCICE v3, right? Lets do this directly on the main branch.

2024-03-07 12:23 UTC, IshaanDesai commented on dune-precice/dune-precice/couplinginterface.hh
> +      void read_blockvector_data(VectorType &dune_data, double dt);
It is probably a good idea to rename these function to be similar to the new preCICE API. Older names will confuse future users.

2024-03-07 12:24 UTC, IshaanDesai requested changes
I noticed some more things that need changes/discussions.

2024-03-19 15:37 UTC, Fujikawas commented
I have tested the solver for the perpendicular flap tutorial, it could provide the same displacement curve (considering the amplitude and frequency) as the reference data.

2024-03-19 16:32 UTC, IshaanDesai commented
I confirm that running the perpendicular flap tutorial with the changes here gives correct results:

![image](https://github.com/precice/dune-adapter/assets/44898158/004d7796-362b-4705-a7b6-0a5a4ccc74da)

2024-03-19 16:33 UTC, IshaanDesai approved these changes

2024-03-19 16:35 UTC, merged